# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - run: echo hello
    # job steps...

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  jobOnFailure:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: ${{ failure() }}
    steps:
      - name: Run if any previous job failed
        run: echo "A previous job failed!"
